# Generated by Django 5.0.6 on 2024-05-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
