# Generated by Django 5.0.6 on 2024-05-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_app', '0002_perfil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
