# Generated by Django 5.0.6 on 2024-05-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_app', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfil_app.perfilusuario'),
            preserve_default=False,
        ),
    ]
