# Generated by Django 5.0.6 on 2024-05-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_app', '0005_perfil_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
    ]
