# Generated by Django 5.0.6 on 2024-09-04 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_app', '0001_initial'),
        ('productos_app', '0002_producto_descripcion_producto_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_item', to='productos_app.producto'),
        ),
    ]
